from typing import Any, Dict, List, Set, Union

class Key:
    def __init__(self, name: str,
                 data: Dict[str, Union[str, bool, Dict[str, Union[str, List[str]]]]],
                 update: List[str], skip: Set[str], trial_run: bool) -> None: ...
    def generate(self) -> None: ...
    keyname: str = ...
